import mongoose from "mongoose";

const schema: mongoose.Schema = new mongoose.Schema({
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    auto: true,
  },
  Address: String,
  City: String,
  DOB: String,
  FamilySize: String,
  FirstChoiceSchool: String,
  FirstChoiceSchoolID: String,
  FirstName: String,
  FosterCare: String,
  Gender: String,
  Income: String,
  IncomeFrequency: String,
  LastName: String,
  MiddleName: String,
  PG_1_Email: String,
  PG_1_First: String,
  PG_1_Last: String,
  PG_1_Phone: String,
  PG_2_Email: String,
  PG_2_First: String,
  PG_2_Last: String,
  PG_2_Phone: String,
  Primary_Language: String,
  Referral: String,
  SecondChoiceSchool: String,
  Siblings: String,
  SiblingsInfo: String,
  State: String,
  Submitted: String,
  Zip: String,
  CalcIncome: Number,
  CalcIncomeFrequency: Number,
  CalcIncomeFrequencyOverride: String,
  CalcFamilySize: Number,
  CalcFPL: Number,
  CalcQuintile: Number,
  Eligibility: String,
  SchoolYear: String,
});

// intake model
export default mongoose.model("Intake", schema);
